from  fhirclient.models import account,\
                                activitydefinition,\
                                adverseevent,\
                                allergyintolerance,\
                                appointment,\
                                appointmentresponse,\
                                auditevent,\
                                basic,\
                                binary,\
                                biologicallyderivedproduct,\
                                bundle,\
                                capabilitystatement,\
                                careplan,\
                                careteam,\
                                catalogentry,\
                                chargeitem,\
                                chargeitemdefinition,\
                                claim,\
                                claimresponse,\
                                clinicalimpression,\
                                codesystem,\
                                communication,\
                                communicationrequest,\
                                compartmentdefinition,\
                                composition,\
                                conceptmap,\
                                condition,\
                                consent,\
                                contract,\
                                coverage,\
                                coverageeligibilityrequest,\
                                coverageeligibilityresponse,\
                                detectedissue,\
                                device,\
                                devicedefinition,\
                                devicemetric,\
                                devicerequest,\
                                deviceusestatement,\
                                diagnosticreport,\
                                documentmanifest,\
                                documentreference,\
                                domainresource,\
                                effectevidencesynthesis,\
                                endpoint,\
                                enrollmentrequest,\
                                enrollmentresponse,\
                                episodeofcare,\
                                eventdefinition,\
                                examplescenario,\
                                explanationofbenefit,\
                                familymemberhistory,\
                                flag,\
                                goal,\
                                graphdefinition,\
                                group,\
                                guidanceresponse,\
                                healthcareservice,\
                                imagingstudy,\
                                immunization,\
                                immunizationevaluation,\
                                immunizationrecommendation,\
                                implementationguide,\
                                insuranceplan,\
                                invoice,\
                                library,\
                                linkage,\
                                list,\
                                location,\
                                measure,\
                                media,\
                                medication,\
                                medicationadministration,\
                                medicationdispense,\
                                medicationknowledge,\
                                medicationrequest,\
                                medicationstatement,\
                                medicinalproduct,\
                                medicinalproductauthorization,\
                                medicinalproductcontraindication,\
                                medicinalproductindication,\
                                medicinalproductingredient,\
                                medicinalproductinteraction,\
                                medicinalproductmanufactured,\
                                medicinalproductpackaged,\
                                medicinalproductpharmaceutical,\
                                messagedefinition,\
                                messageheader,\
                                molecularsequence,\
                                namingsystem,\
                                nutritionorder,\
                                observation,\
                                observationdefinition,\
                                operationdefinition,\
                                operationoutcome,\
                                organization,\
                                organizationaffiliation,\
                                patient,\
                                paymentnotice,\
                                paymentreconciliation,\
                                person,\
                                plandefinition,\
                                practitioner,\
                                practitionerrole,\
                                procedure,\
                                provenance,\
                                questionnaire,\
                                questionnaireresponse,\
                                relatedperson,\
                                requestgroup,\
                                researchdefinition,\
                                researchelementdefinition,\
                                researchstudy,\
                                researchsubject,\
                                resource,\
                                riskassessment,\
                                riskevidencesynthesis,\
                                schedule,\
                                searchparameter,\
                                servicerequest,\
                                slot,\
                                specimen,\
                                specimendefinition,\
                                structuredefinition,\
                                structuremap,\
                                subscription,\
                                substance,\
                                substancespecification,\
                                supplydelivery,\
                                supplyrequest,\
                                task,\
                                terminologycapabilities,\
                                testreport,\
                                testscript,\
                                valueset,\
                                verificationresult,\
                                visionprescription